site_name: crysm
site_url: https://iverks.github.io/crysm/
theme:
  name: "material"
  palette:
    scheme: slate
    primary: deep orange
    accent: green
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
markdown_extensions:
  - toc
  - abbr
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.pathconverter

plugins:
  - search:
  - mkdocs-typer2:
watch:
  - src
nav:
  - Crysm: index.md
  - Reference: reference.md
  - PDF guide: cred_guide.pdf
