[project]
name = "cred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pydantic>=2.9.2",
    "pyparsing>=3.1.4",
    "typer>=0.12.5",
]
